package br.edu.acad.ifma.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgendamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendamentoAllPropertiesEquals(Agendamento expected, Agendamento actual) {
        assertAgendamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertAgendamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendamentoAllUpdatablePropertiesEquals(Agendamento expected, Agendamento actual) {
        assertAgendamentoUpdatableFieldsEquals(expected, actual);
        assertAgendamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendamentoAutoGeneratedPropertiesEquals(Agendamento expected, Agendamento actual) {
        assertThat(actual)
            .as("Verify Agendamento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendamentoUpdatableFieldsEquals(Agendamento expected, Agendamento actual) {
        assertThat(actual)
            .as("Verify Agendamento relevant properties")
            .satisfies(a -> assertThat(a.getPeriodicidade()).as("check periodicidade").isEqualTo(expected.getPeriodicidade()))
            .satisfies(a -> assertThat(a.getHoraEnvio()).as("check horaEnvio").isEqualTo(expected.getHoraEnvio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendamentoUpdatableRelationshipsEquals(Agendamento expected, Agendamento actual) {
        // empty method
    }
}
